spring.application.name=Chat Bot Application
server.port=8081

# This is all database configuration
spring.datasource.url= jdbc:mysql://localhost:3306/ chatbot_application_database
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# This is hibernate configuration you have to do it

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect